version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy_.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: heartBeat.sh
      timeout: 30
      runas: ec2-user
