version: 0.2

phases:
  build:
    commands:
      - echo [HOLA_SERVER_DEPLOYMENT_SYSTEM]
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo [HOLA_SERVER_DEPLOYMENT_SYSTEM]
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - appspec.yml
    - build/libs/*.jar
    - scripts/**
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'