# buildspec.yml

version: 0.2

phases:
  build:
    commands:
      - echo START BUILD
      - chmod +x ./gradlew
      - ./gradlew clean build
  post_build:
    commands:
      - echo START POST_BUILD
      - echo $(basename ./build/libs/*.jar)
      - pwd
cache:
  paths:
    - '/root/.gradle/caches/**/*'