version: "3"
services:
  app:
    container_name: hola-server-application
    image: openjdk:11-jdk
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["./gradlew", "bootrun"]
    restart: always