version: "3"
services:
  db:
    container_name: hola-local-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: hola-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: hola-db-pw
      MYSQL_ROOT_PASSWORD: hola-root-db-pw
    volumes:
      - ./db/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    restart: always
  app:
    container_name: hola-server-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - db
    restart: always
