ALTER TABLE `Category_Store` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Category_Store` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Category_Store` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Img_Review` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Img_Review` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Img_Review` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Img_Store` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Img_Store` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Img_Store` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Item` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Item` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Item` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

