ALTER TABLE `Category_Store` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Category_Store` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Category_Store` MODIFY COLUMN `removed_at` TIMESTAMP NULL;