ALTER TABLE `Category_Store` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Category_Store` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Category_Store` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Img_Review` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Img_Review` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Img_Review` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Img_Store` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Img_Store` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Img_Store` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Item` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Item` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Item` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Recommendation` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Recommendation` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Recommendation` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Review` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Review` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Review` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Review_Tag` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Review_Tag` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Review_Tag` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Review_Tag_Log` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Review_Tag_Log` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Review_Tag_Log` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `Store` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Store` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `Store` MODIFY COLUMN `removed_at` TIMESTAMP NULL;

ALTER TABLE `User` MODIFY COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `User` MODIFY COLUMN `modified_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `User` MODIFY COLUMN `removed_at` TIMESTAMP NULL;