RENAME TABLE Category_Store TO category_store,
    Customer_Satisfaction TO customer_satisfaction,
    Img_Review TO img_review,
    Img_Store TO img_store,
    Item TO item,
    Recommendation TO recommendation,
    Review TO review,
    Review_Tag TO review_tag,
    Review_Tag_Log TO review_tag_log,
    Store TO store,
    User To user